### ISSUE TITLE
Basic Auth not working

### ISSUE THREAD

**Issue by TiiFuchs** [Sammyjo20/saloon-http-sender#7]
It seems that BasicAuth does not work.

Using the HttpSender, the `$this->withBasicAuth(...)` inside `__construct()` does not seem to work.

There is no additional header that is send in the request.

Changing the Sender to a GuzzleSender makes it work flawlessly.

**Comment by Sammyjo20** [comment]
Ah I know this issue... It's because we're using `config()->set()` here in the `HttpSender` whereas we need to use `->merge()`

![Screenshot 2023-03-14 at 11 48 28](https://user-images.githubusercontent.com/29132017/224992056-539ed5a8-07e5-4c3c-b52b-584b5a1141d8.png)

I will fix this when I get home later ✌️

**Comment by Sammyjo20** [comment]
Hey @TiiFuchs this is now fixed in the latest release! 😎

**Comment by TiiFuchs** [comment]
I'll try it out as soon as I can. Probably tomorrow... :)
